version: '3'
services:
  holder:
    image: acapy-test
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start
        -e http://holder:3000
        --webhook-url http://webhook-listener:8080
        --label holder
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --debug-connections
        --preserve-exchange-records
        --wallet-type indy
        --wallet-name default
        --wallet-key insecure
        --log-level debug
        --auto-provision
        --notify-revocation
        --monitor-revocation-notification
        --public-invites
    depends_on:
      - tails
      - webhook-listener

  issuer:
    image: acapy-test
    ports:
      - 3002:3000
      - 3003:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start
        -e http://issuer:3000
        --tails-server-base-url http://tails:6543
        --webhook-url http://webhook-listener:8080
        --label issuer
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --debug-connections
        --preserve-exchange-records
        --wallet-type indy
        --wallet-name default
        --wallet-key insecure
        --log-level debug
        --auto-provision
        --notify-revocation
        --monitor-revocation-notification
        --public-invites
    depends_on:
      - tails
      - webhook-listener

  verifier:
    image: acapy-test
    ports:
      - 3004:3000
      - 3005:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start
        -e http://verifier:3000
        --tails-server-base-url http://tails:6543
        --webhook-url http://webhook-listener:8080
        --label verifier
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --debug-connections
        --preserve-exchange-records
        --wallet-type indy
        --wallet-name default
        --wallet-key insecure
        --log-level debug
        --auto-provision
        --notify-revocation
        --monitor-revocation-notification
    depends_on:
      - tails
      - webhook-listener

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

  webhook-listener:
    image: mendhak/http-https-echo:18
    environment:
      - HTTP_PORT=8080

  demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.demo
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=holder:3000,issuer:3000
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - HOLDER=http://holder:3001
      - ISSUER=http://issuer:3001
      - VERIFIER=http://issuer:3001
    depends_on:
      - holder
      - issuer
