version: '3'
services:
  holder:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: start --arg-file ./configs/holder.yml -e http://holder:3000

  issuer:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    ports:
      - 3002:3000
      - 3003:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start --arg-file ./configs/issuer.yml
        -e http://issuer:3000
        --tails-server-base-url http://tails:6543

  tails:
    image: indy-tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

  demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.demo
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=holder:3000,issuer:3000
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - HOLDER=http://holder:3001
      - ISSUER=http://issuer:3001
    depends_on:
      - holder
      - issuer
      - tails
