FROM python:3.10

WORKDIR /usr/src/app
RUN pip install poetry

RUN mkdir acapy_revocation_demo && touch acapy_revocation_demo/__init__.py
COPY ./pyproject.toml .
COPY ./poetry.lock .
COPY ./README.md .

RUN poetry install
COPY ./acapy_revocation_demo acapy_revocation_demo
COPY ./tests tests

CMD ["poetry", "run", "python", "-m", "acapy_revocation_demo"]
